kind: Cluster
apiVersion: clusterregistry.k8s.io/v1alpha1
metadata:
  name: dr-usa-cloud-1
  labels:
    environment: dr
    location: us-central1
---
kind: ClusterSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: dr-usa-cloud
spec:
  selector:
    matchLabels:
      environment: dr
      location: us-central1
---
kind: Cluster
apiVersion: clusterregistry.k8s.io/v1alpha1
metadata:
  name: dc-singapore-on-prem-1
  labels:
    environment: dc
    location: asia-southeast1
---
kind: ClusterSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: dc-singapore-on-prem
spec:
  selector:
    matchLabels:
      environment: dc
      location: asia-southeast1
